root: true
extends:
- plugin:@mysticatea/es2018
- plugin:@mysticatea/+node
overrides:
- files: "**/shim/*.js"
  extends: plugin:@mysticatea/+modules
  rules:
    "@mysticatea/node/no-unsupported-features/es-syntax":
    - error
    - ignores:
      - modules
